### ISSUE TITLE
Some pages do not update the rich presence

### ISSUE THREAD

**Issue by NetheriteMiner** [TechStudent10/DiscordRPC#8]
I intend to make a PR for this soon (soon might be a while)

**Comment by Rohan-Sangani** [comment]
Pages I intend to add (might end up cutting it down):

Main Menu
Treasure Room
Scratch, Community, Mechanic, Diamond
Vault of Secrets
Basement
Quests
Lists
Paths
Regular shop
Settings
Main levels
Character selection
Shards
Geode customization

**Comment by TechStudent10** [comment]
Gl!

**Comment by Rohan-Sangani** [comment]
I ended up being able to do most of them, but found a few roadblocks:
- The ShopType enum has not been updated to 2.2, so I can only detect the regular shop, scratch, and potbor
- I decided against the basement because it looks creepy to see "player is in the basement"
- I couldn't do Geode customization because DevTools says it's on a layer that isn't documented nor in our headers/bindings so guess not

But, in exchange, here are some of the bonus ones I was able to do:
- Achievements
- The Map
- Regular Vault & Chamber of Time

Also I made a handful of funny mode messages including giving back on track the extreme demon face because it was too convenient
